process.env['GITHUB_EVENT_NAME'] = 'push'
process.env['GITHUB_SHA'] = 'HEAD'
process.env['GITHUB_REF'] = 'refs/heads/master'
process.env['GITHUB_WORKFLOW'] = 'test'
process.env['GITHUB_ACTION'] = 'test'
process.env['GITHUB_ACTOR'] = 'test'
process.env['GITHUB_JOB'] = 'test'
process.env['GITHUB_RUN_NUMBER'] = '1'
process.env['GITHUB_RUN_ID'] = '1'
process.env['GITHUB_REPOSITORY'] ||= process.env['INPUT_REPOSITORY'] || 'serde-rs/serde'

process.env['INPUT_TAG'] ||= 'false'
process.env['INPUT_DIRECTORY'] ||= '.'
process.env['INPUT_DRY-RUN'] ||= 'true'
process.env['INPUT_ARGUMENTS'] ||= ''
process.env['INPUT_GITHUB-TOKEN'] ||= process.env['GITHUB_TOKEN'] || 'skip'
process.env['INPUT_CRATES-TOKEN'] ||= 'skip'
