# Publish all Actions in this repository

name: Publish

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - ".github/**/*"
      - "**/*.md"
      - ".gitignore"
      - ".editorconfig"
      - "LICENSE"
  workflow_dispatch:

permissions:
  contents: write

jobs:

  publish:

    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Node
        uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: Get cache directory path
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Set up cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: |
          pnpm install

      - name: Run tests
        env:
          "GITHUB_TOKEN": ${{ secrets.GITHUB_TOKEN }}
        run: |
          pnpm run test

      - name: Build actions
        run: |
          pnpm run clean
          pnpm run build

      - name: Publish actions
        uses: ./actions/release-actions
